export async function scaffoldCmd(name:string):Promise<string>{
  const nm = name || 'project';
  // Expanded scaffold: write actual starter files to disk
  const fs = await import('fs');
  const path = await import('path');
  const root = path.resolve(process.cwd(), nm);
  if(!fs.existsSync(root)){
    fs.mkdirSync(root, {recursive:true});
    fs.writeFileSync(path.join(root,'README.md'),`# ${nm}\n\nGenerated by locall_llm_unhinged MVP scaffold.`, 'utf8');
    fs.writeFileSync(path.join(root,'package.json'), JSON.stringify({name:nm, version:'0.1.0', private:true}, null, 2));
  }
  return `Scaffolded starter for ${nm} at ${root}`;
}
